name: Deploy Portfolio

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-client/**'
      - 'portfolio-backoffice/**'
      - 'portfolio-backend/**'
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [portfolio-client, portfolio-backoffice, portfolio-backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

  deploy:
    name: Deploy Services
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [portfolio-client, portfolio-backoffice, portfolio-backend]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/${{ matrix.service }}
            docker-compose pull
            docker-compose down
            docker-compose up -d